version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/scripts"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/infra/aws"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/infra/azure"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
